image:
  repository: docker.io/minjiki222/cloudbread-backend
  tag: "89da20e"
  pullPolicy: IfNotPresent

ingress:
  host: cloudbread.133.186.213.185.nip.io   # NHN Cloud에서 노출된 Ingress 도메인

envFromSecretName: app-env                  # 이미 클러스터에 있는 Secret 이름
pvc:
  claimName: uploads-pvc                    # 이미 만든 PVC 이름
